# Site
name: "Metro"
title_suffix: "Metro | NYC Subway Alerts | Real-Time Updates for Smooth Commutes"
title: "NYC Subway Alerts | Real-Time Updates for Smooth Commutes"
description: "NYC Subway Alerts | Real-Time Updates for Smooth Commutese"
meta_description: "NYC Subway Alerts | Real-Time Updates for Smooth Commutes"
logo: "/assets/images/logo.png"
favicon: "/assets/images/favicon.ico"
baseurl: "https://www.smoothcommutes.com"
permalink: /:categories/:title
email: ""
google_analytics: ""
future: true

# Authors
authors:
  reece:
    name: Reece
    display_name: Reece Williams 
    gravatar:
    email: ""
    description: ""
